# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: risk-agent
metadata:
  template: risk-agent@0.0.1-beta

hooks:
  postdeploy:
    posix:
      shell: sh
      run: |
        echo "Configuring internal function key..."
        ./scripts/configure-function-key.sh

services:
  api:
    project: ./src/ElasticOn.RiskAgent.Demo.Functions
    language: dotnet
    host: function
  web:
    project: ./src/ElasticOn.RiskAgent.Demo.Web
    language: dotnet
    host: staticwebapp
    dist: wwwroot

infra:
  provider: bicep
  path: infra

pipeline:
  provider: github
  variables:
    - AZURE_LOCATION
    - AZURE_SUBSCRIPTION_ID